implement dim statement (#283)
sjbarag/brs pull request #531
Opened 2020-09-04 21:20 UTC by strattonbrazil

This implements the dim statement for as requested for #283. It doesn't match Roku's spec exactly as Roku's dim will leave the bottom-level arrays unexpanded but resizeable. When brs supports resizeable arrays (#530) we can come back and update this code to match the spec.

2020-09-04 22:41 UTC, sjbarag requested changes
Looking good!  Nice job jumping into the parser — this is almost perfect.  I've got two small requests that should help out with error checking and location tracking, but they shouldn't take terribly long to implement and will make a big difference.

Thanks for the thorough comments, @strattonbrazil !

2020-09-08 18:28 UTC, strattonbrazil commented on src/parser/Parser.ts
> +            let name = advance();
Will fix.

2020-09-08 18:30 UTC, strattonbrazil commented on src/parser/Parser.ts
> +                if (check(Lexeme.Comma)) advance();
Commas aren't optional (in the spec), but I need to step over them if present either before or after. I guess this current implementation does make them optional. Thoughts?

2020-09-08 18:31 UTC, strattonbrazil commented on src/parser/Statement.ts
> +    accept<R>(_visitor: Visitor<R>): BrsType {
Will fix.

2020-09-08 18:35 UTC, strattonbrazil commented on src/parser/Statement.ts
> +            end: this.tokens.dim.location.end,
I'm using the match() in the while loop. Is there a function to get the most recent token, or would I need to save the match() response (ex. while-true loop)?

2020-09-08 20:20 UTC, sjbarag commented on src/parser/Parser.ts
> +                if (check(Lexeme.Comma)) advance();
You might have some luck parsing this with a single `expression()` outside the loop, then requiring a comma and an expression inside the loop!  Something like:

```typescript
let dimensions: Expression[] = [ expression() ];
while(!match(Lexeme.RightSquare)) {
    consume("Expected ',' after expression in 'dim' statement", Lexeme.Comma);
    dimensions.push(expression());
}
```

Which should work on the assumption that the pre-loop `expression()` call throws an error?  You could always `try/catch` to provide better error messaging like you do below on line 1176 😃

2020-09-08 20:20 UTC, sjbarag commented on src/parser/Statement.ts
> +            end: this.tokens.dim.location.end,
You've got (at least) two options!

```typescript
let rightSquare: Token;
while (rightSquare = peek(Lexeme.RightSquare) && !match(Lexeme.RightSquare)) {
}
```

or rely on the fact that we break out of the `while` loop immediately when a `]` is encountered and use `previous()`, e.g.:

```typescript
while (!match(Lexeme.RightSquare)) {
    // …
}
let rightSquare = previous();
```

The second feels a bit more clear, but anything along those lines should be fine!

2020-09-09 18:33 UTC, sjbarag approved these changes
Thanks for the updates @strattonbrazil !

2020-09-09 18:35 UTC, merged